// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadInitialData() {
  return window['go']['main']['App']['LoadInitialData']();
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}
