// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNewProfile(arg1:Array<main.ProfileEntity>,arg2:string):Promise<Array<main.ProfileEntity>>;

export function DeleteProfile(arg1:number):Promise<void>;

export function LoadInitialData():Promise<main.CoreData>;

export function SaveProfile(arg1:string,arg2:boolean,arg3:number):Promise<void>;

export function SaveProject(arg1:string,arg2:string):Promise<void>;
