// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewProfile(arg1, arg2) {
  return window['go']['main']['App']['CreateNewProfile'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function LoadInitialData() {
  return window['go']['main']['App']['LoadInitialData']();
}

export function SaveProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2, arg3);
}

export function SaveProject(arg1, arg2) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2);
}
